package Spark.Config.SparkConf.Init.Storage

case class IfapaAemetFormatSingleStationMeteoInfoDirs(data: String)
case class IfapaAemetFormatSingleStationMeteoInfoFilenames(data: String)
case class IfapaAemetFormatSingleStationMeteoInfoFilepaths(data: String)
case class IfapaAemetFormatSingleStationMeteoInfo(dirs: IfapaAemetFormatSingleStationMeteoInfoDirs, filenames: IfapaAemetFormatSingleStationMeteoInfoFilenames, filepaths: IfapaAemetFormatSingleStationMeteoInfoFilepaths)

case class IfapaAemetFormatSingleStationInfoDirs(data: String)
case class IfapaAemetFormatSingleStationInfoFilenames(data: String)
case class IfapaAemetFormatSingleStationInfoFilepaths(data: String)
case class IfapaAemetFormatSingleStationInfo(dirs: IfapaAemetFormatSingleStationInfoDirs, filenames: IfapaAemetFormatSingleStationInfoFilenames, filepaths: IfapaAemetFormatSingleStationInfoFilepaths)

case class IfapaAemetFormatConf(baseDir: String, singleStationMeteoInfo: IfapaAemetFormatSingleStationMeteoInfo, singleStationInfo: IfapaAemetFormatSingleStationInfo)
