import os

from pathlib import Path

# ------------------------
# ----   KEY NAMES   ----
# ------------------------

# ENV
K_AWS_S3_ENDPOINT = "AWS_S3_ENDPOINT"
K_STORAGE_PREFIX = "STORAGE_PREFIX"
K_STORAGE_BASE_DIR = "STORAGE_BASE_DIR"

# STORAGE
K_RESOURCES_COUNTRIES_SHAPEFILE_DIR = "../Resources/countries_shapes"
K_OUTPUT_DIR_NAME = "output"

# FORMATTERS
K_FORMATTER_TIMESTAMP = "timestamp"
K_FORMATTER_TIMESTAMP_YEAR = "timestamp_year"

FORMATTERS_LIST = [
    K_FORMATTER_TIMESTAMP,
    K_FORMATTER_TIMESTAMP_YEAR
]

# TABLE ALIGNS
K_TABLE_ALIGNS_LEFT = "left"
K_TABLE_ALIGNS_CENTER = "center"
K_TABLE_ALIGNS_RIGHT = "right"

TABLE_ALIGNS_LIST = [
    K_TABLE_ALIGNS_LEFT,
    K_TABLE_ALIGNS_CENTER,
    K_TABLE_ALIGNS_RIGHT
]

# MONTHS SPANISH
K_MONTHS_SP_ENE = "Ene"
K_MONTHS_SP_FEB = "Feb"
K_MONTHS_SP_MAR = "Mar"
K_MONTHS_SP_ABR = "Abr"
K_MONTHS_SP_MAY = "May"
K_MONTHS_SP_JUN = "Jun"
K_MONTHS_SP_JUL = "Jul"
K_MONTHS_SP_AGO = "Ago"
K_MONTHS_SP_SEP = "Sep"
K_MONTHS_SP_OCT = "Oct"
K_MONTHS_SP_NOV = "Nov"
K_MONTHS_SP_DIC = "Dic"

MONTHS_SP_LIST = [
    K_MONTHS_SP_ENE,
    K_MONTHS_SP_FEB,
    K_MONTHS_SP_MAR,
    K_MONTHS_SP_ABR,
    K_MONTHS_SP_MAY,
    K_MONTHS_SP_JUN,
    K_MONTHS_SP_JUL,
    K_MONTHS_SP_AGO,
    K_MONTHS_SP_SEP,
    K_MONTHS_SP_OCT,
    K_MONTHS_SP_NOV,
    K_MONTHS_SP_DIC
]

# SPAIN GEOGRAPHIC LOCATIONS
K_SPAIN_GEOGRAPHIC_LOCATIONS_CONTINENTAL = "continental"
K_SPAIN_GEOGRAPHIC_LOCATIONS_CANARY_ISLANDS = "canary_islands"

SPAIN_GEOGRAPHIC_LOCATIONS_LIST = [
    K_SPAIN_GEOGRAPHIC_LOCATIONS_CONTINENTAL,
    K_SPAIN_GEOGRAPHIC_LOCATIONS_CANARY_ISLANDS
]

# ---------------------
# ----   STORAGE   ----
# ---------------------

STORAGE_PREFIX = os.getenv(K_STORAGE_PREFIX)
STORAGE_BASE_DIR = Path(os.getenv(K_STORAGE_BASE_DIR))
OUTPUT_BASE_DIR = (STORAGE_BASE_DIR / Path(K_OUTPUT_DIR_NAME))

STORAGE_RESOURCES_COUNTRIES_SHAPEFILE = Path(K_RESOURCES_COUNTRIES_SHAPEFILE_DIR).resolve()

# --------------------
# ----   AWS S3   ----
# --------------------

AWS_S3_ENDPOINT = os.getenv(K_AWS_S3_ENDPOINT)

# ----------------------------------------
# ----   HEAT MAP CHART COORDINATES   ----
# ----------------------------------------

LONG_LOWER_BOUND_SPAIN_CONTINENTAL, LONG_UPPER_BOUND_SPAIN_CONTINENTAL = (-9.5, 4.5)
LAT_LOWER_BOUND_SPAIN_CONTINENTAL, LAT_UPPER_BOUND_SPAIN_CONTINENTAL = (35.0, 44.0)

LONG_LOWER_BOUND_SPAIN_CANARY_ISLAND, LONG_UPPER_BOUND_SPAIN_CANARY_ISLAND = (-18.25, -13.25)
LAT_LOWER_BOUND_SPAIN_CANARY_ISLAND, LAT_UPPER_BOUND_SPAIN_CANARY_ISLAND = (27.5, 29.5)