@startuml
participant "PlotGenerator" as PLOT_GENERATOR
participant "Climograph" as CLIMOGRAPH
participant "JSONUtils" as JSON_UTILS
participant "Plot API" as PLOT_API

PLOT_GENERATOR -> CLIMOGRAPH : generate()
activate CLIMOGRAPH

loop each climateGroup
    CLIMOGRAPH -> CLIMOGRAPH : foreach climateGroup

    loop each climateRecord
        CLIMOGRAPH -> CLIMOGRAPH : foreach climateRecord

        loop each location
            CLIMOGRAPH -> JSON_UTILS : readJSON(stationInfo)
            JSON_UTILS --> CLIMOGRAPH : station JSON

            CLIMOGRAPH -> PLOT_API : generatePlot(climograph)
            PLOT_API --> CLIMOGRAPH : ok
        end
    end
end

CLIMOGRAPH --> PLOT_GENERATOR : done
deactivate CLIMOGRAPH

@enduml
