@startuml
participant "PlotGenerator" as PLOT_GENERATOR
participant "SingleParamStudies" as SINGLE_PARAM_STUDIES
participant "JSONUtils" as JSON_UTILS
participant "Plot API" as PLOT_API

PLOT_GENERATOR -> SINGLE_PARAM_STUDIES : generate()
activate SINGLE_PARAM_STUDIES

loop each meteoParam
    SINGLE_PARAM_STUDIES -> SINGLE_PARAM_STUDIES : foreach meteoParam

    group TOP 10
        loop each order
            loop each temporal
                SINGLE_PARAM_STUDIES -> PLOT_API : generatePlot(top10)
                PLOT_API --> SINGLE_PARAM_STUDIES : ok
            end
        end
    end

    group TOP 5 INC
        loop each order
            SINGLE_PARAM_STUDIES -> PLOT_API : generatePlot(top5Inc)
            PLOT_API --> SINGLE_PARAM_STUDIES : ok
        end
    end

    group EVOLUTION
        loop each state
            SINGLE_PARAM_STUDIES -> JSON_UTILS : readJSON(station2024)
            JSON_UTILS --> SINGLE_PARAM_STUDIES : station JSON
            SINGLE_PARAM_STUDIES -> PLOT_API : generatePlot(evol2024)
            PLOT_API --> SINGLE_PARAM_STUDIES : ok

            SINGLE_PARAM_STUDIES -> JSON_UTILS : readJSON(stationGlobal)
            JSON_UTILS --> SINGLE_PARAM_STUDIES : station JSON
            SINGLE_PARAM_STUDIES -> PLOT_API : generatePlot(evolYearlyGroup)
            PLOT_API --> SINGLE_PARAM_STUDIES : ok
        end
    end

    group HEATMAP 2024
        loop each location
            SINGLE_PARAM_STUDIES -> PLOT_API : generatePlot(heatMap2024)
            PLOT_API --> SINGLE_PARAM_STUDIES : ok
        end
    end

end

SINGLE_PARAM_STUDIES --> PLOT_GENERATOR : done
deactivate SINGLE_PARAM_STUDIES

@enduml
