@startuml
actor User

participant "PlotGenerator" as PLOT_GENERATOR
participant "Stations" as STATIONS
participant "Climograph" as CLIMOGRAPH
participant "SingleParamStudies" as SINGLE_PARAM_STUDIES
participant "InterestingStudies" as INTERESTING_STUDIES

User -> PLOT_GENERATOR : generate()
activate PLOT_GENERATOR

PLOT_GENERATOR -> STATIONS : Stations.generate()
STATIONS --> PLOT_GENERATOR : done

PLOT_GENERATOR -> CLIMOGRAPH : Climograph.generate()
CLIMOGRAPH --> PLOT_GENERATOR : done

PLOT_GENERATOR -> SINGLE_PARAM_STUDIES : SingleParamStudies.generate()
SINGLE_PARAM_STUDIES --> PLOT_GENERATOR : done

PLOT_GENERATOR -> INTERESTING_STUDIES : InterestingStudies.generate()
INTERESTING_STUDIES --> PLOT_GENERATOR : done

PLOT_GENERATOR --> User : finished
deactivate PLOT_GENERATOR

@enduml
