@startuml
autonumber

actor Client

participant "JSONStorageBackend" as JSON_STORAGE_BACKEND
participant "Storage" as STORAGE
participant "S3StorageBackend" as S3_STORAGE_BACKEND
participant "LocalStorageBackend" as LOCAL_STORAGE_BACKEND
participant "ujson" as UJSON

Client -> JSON_STORAGE_BACKEND : readJSON(path)
activate JSON_STORAGE_BACKEND

JSON_STORAGE_BACKEND -> STORAGE : read(path)
activate STORAGE

STORAGE -> STORAGE : selectS3orLocal(prefix + path)

alt Path is S3
    STORAGE -> S3_STORAGE_BACKEND : read(bucket, key, endpoint)
    activate S3_STORAGE_BACKEND
    S3_STORAGE_BACKEND --> STORAGE : tmpFile(Path)
    deactivate S3_STORAGE_BACKEND
else Path is Local
    STORAGE -> LOCAL_STORAGE_BACKEND : read(key)
    activate LOCAL_STORAGE_BACKEND
    LOCAL_STORAGE_BACKEND --> STORAGE : tmpFile(Path)
    deactivate LOCAL_STORAGE_BACKEND
end

STORAGE --> JSON_STORAGE_BACKEND : tmpFile(Path)
deactivate STORAGE

JSON_STORAGE_BACKEND -> UJSON : read(content)
activate UJSON
UJSON --> JSON_STORAGE_BACKEND : json(Value)
deactivate UJSON

JSON_STORAGE_BACKEND --> Client : Either.Right(json)
deactivate JSON_STORAGE_BACKEND


== WRITE JSON ==

Client -> JSON_STORAGE_BACKEND : writeJSON(path, json)
activate JSON_STORAGE_BACKEND

JSON_STORAGE_BACKEND -> JSON_STORAGE_BACKEND : create temp file
JSON_STORAGE_BACKEND -> UJSON : write(json)
activate UJSON
UJSON --> JSON_STORAGE_BACKEND : jsonString
deactivate UJSON

JSON_STORAGE_BACKEND -> STORAGE : write(path, tmpFile)
activate STORAGE

STORAGE -> STORAGE : selectS3orLocal(prefix + path)

alt Path is S3
    STORAGE -> S3_STORAGE_BACKEND : write(bucket, key, tmpFile)
    activate S3_STORAGE_BACKEND
    S3_STORAGE_BACKEND --> STORAGE : success
    deactivate S3_STORAGE_BACKEND
else Path is Local
    STORAGE -> LOCAL_STORAGE_BACKEND : write(key, tmpFile)
    activate LOCAL_STORAGE_BACKEND
    LOCAL_STORAGE_BACKEND --> STORAGE : success
    deactivate LOCAL_STORAGE_BACKEND
end

STORAGE --> JSON_STORAGE_BACKEND : success
deactivate STORAGE

JSON_STORAGE_BACKEND --> Client : Either.Right(path)
deactivate JSON_STORAGE_BACKEND

@enduml
