@startuml
actor User

participant "SparkManager" as SPARK_MANAGER
participant "SparkSessionManager" as SPARK_SESSION_MANAGER
participant "SparkSessionCore" as SPARK_SESSION_CORE
participant "Storage" as STORAGE

User -> SPARK_MANAGER : execute()
activate SPARK_MANAGER

== Start Spark ==

SPARK_MANAGER -> SPARK_SESSION_MANAGER : createSparkSessionCore()
activate SPARK_SESSION_MANAGER

SPARK_SESSION_MANAGER -> STORAGE : read AEMET allStationInfo Parquet (raw)
STORAGE --> SPARK_SESSION_MANAGER : stations raw DF
SPARK_SESSION_MANAGER -> SPARK_SESSION_MANAGER : formatAllStationsDataframe(stations raw DF)
SPARK_SESSION_MANAGER -> SPARK_SESSION_MANAGER : persist allStations DF

SPARK_SESSION_MANAGER -> STORAGE : read AEMET allMeteoInfo Parquet (raw)
STORAGE --> SPARK_SESSION_MANAGER : meteo raw DF
SPARK_SESSION_MANAGER -> SPARK_SESSION_MANAGER : formatAllMeteoInfoDataframe(meteo raw DF)
SPARK_SESSION_MANAGER -> SPARK_SESSION_MANAGER : persist allMeteoInfo DF

SPARK_SESSION_MANAGER --> SPARK_MANAGER : SparkSessionCore
deactivate SPARK_SESSION_MANAGER

SPARK_MANAGER -> SPARK_SESSION_CORE : startSparkSession()
activate SPARK_SESSION_CORE
SPARK_SESSION_CORE -> SPARK_SESSION_CORE : materialize sessionDataframes.allStations.count()
SPARK_SESSION_CORE -> SPARK_SESSION_CORE : materialize sessionDataframes.allMeteoInfo.count()
SPARK_SESSION_CORE --> SPARK_MANAGER : session started
deactivate SPARK_SESSION_CORE

== End Spark ==

SPARK_MANAGER -> SPARK_SESSION_CORE : endSparkSession()
activate SPARK_SESSION_CORE
SPARK_SESSION_CORE -> SPARK_SESSION_CORE : unpersist session DataFrames
SPARK_SESSION_CORE -> SPARK_SESSION_CORE : stop SparkSession
SPARK_SESSION_CORE --> SPARK_MANAGER : ended
deactivate SPARK_SESSION_CORE

SPARK_MANAGER --> User : finished
deactivate SPARK_MANAGER

@enduml
