@startuml
actor User

participant "App" as APP

== DATA EXTRACTION ==

participant "AemetAPIClient" as AEMET
participant "AEMET API" as AEMET_API
participant "IfapaAPIClient" as IFAPA
participant "IFAPA API" as IFAPA_API
participant "IfapaToAemetConverter" as IFAPA_TO_AEMET
participant "DataReformatter" as DATA_REFORMAT
participant "AemetDataReformatter" as AEMET_REFMT
participant "IfapaDataReformatter" as IFAPA_REFMT
participant "Storage" as STORAGE

User -> APP : start app

activate APP
APP -> STORAGE : get constants
STORAGE --> APP : constants

APP -> AEMET : start AEMET data extraction
activate AEMET
AEMET -> AEMET_API : get AEMET data
AEMET_API --> AEMET : ok
AEMET -> STORAGE : save AEMET data
STORAGE --> AEMET : saved
AEMET --> APP : end AEMET data extraction
deactivate AEMET

APP -> IFAPA : start IFAPA data extraction
activate IFAPA
IFAPA -> IFAPA_API : get IFAPA data
IFAPA_API --> IFAPA : ok
IFAPA -> STORAGE : save IFAPA data
STORAGE --> IFAPA : saved
IFAPA --> APP : end IFAPA data extraction
deactivate IFAPA

APP -> IFAPA_TO_AEMET : start IFAPA to AEMET format
activate IFAPA_TO_AEMET
IFAPA_TO_AEMET -> STORAGE : save converted IFAPA to AEMET data
STORAGE --> IFAPA_TO_AEMET : saved
IFAPA_TO_AEMET --> APP : end IFAPA to AEMET format
deactivate IFAPA_TO_AEMET

APP -> DATA_REFORMAT : start reformat data
activate DATA_REFORMAT

DATA_REFORMAT -> AEMET_REFMT : reformatStationsData()
activate AEMET_REFMT
AEMET_REFMT -> STORAGE : write stations Parquet
STORAGE --> AEMET_REFMT : saved
AEMET_REFMT --> DATA_REFORMAT : done
deactivate AEMET_REFMT

DATA_REFORMAT -> AEMET_REFMT : reformatMeteoData()
activate AEMET_REFMT
AEMET_REFMT -> STORAGE : write meteo Parquet
STORAGE --> AEMET_REFMT : saved
AEMET_REFMT --> DATA_REFORMAT : done
deactivate AEMET_REFMT

DATA_REFORMAT -> IFAPA_REFMT : reformatStationsData()
activate IFAPA_REFMT
IFAPA_REFMT -> STORAGE : write IFAPA station Parquet
STORAGE --> IFAPA_REFMT : saved
IFAPA_REFMT --> DATA_REFORMAT : done
deactivate IFAPA_REFMT

DATA_REFORMAT -> IFAPA_REFMT : reformatMeteoData()
activate IFAPA_REFMT
IFAPA_REFMT -> STORAGE : write IFAPA meteo Parquet
STORAGE --> IFAPA_REFMT : saved
IFAPA_REFMT --> DATA_REFORMAT : done
deactivate IFAPA_REFMT

DATA_REFORMAT --> APP : end reformat data
deactivate DATA_REFORMAT

@enduml
