@startuml
title Execution of getTopNClimateParamInALapse()

start

:Input parameters
climateParam: String
aggMethodName: String
paramNameToShow: String
startDate: String
endDate: Option(String)
topN: Int
highest: Boolean;

:Load allMeteoInfo DataFrame;
:Load allStations DataFrame;

if (endDate defined?) then (Yes)
    :FILTER fecha BETWEEN startDate AND endDate;
else (No)
    :FILTER YEAR(fecha) == startDate;
endif

:FILTER climateParam IS NOT NULL;

:GROUP BY indicativo;

:AGGREGATE
  climateParam USING aggMethodName AS grouped_value;

:JOIN allStations ON indicativo INNER;

:SELECT
  indicativo AS station_id,
  nombre AS station_name,
  provincia AS state,
  ROUND(grouped_value, 1) AS paramNameToShow,
  latitud AS lat_dms,
  longitud AS long_dms,
  altitud AS altitude;

if (highest?) then (Yes)
    :ORDER BY paramNameToShow DESC;
else (No)
    :ORDER BY paramNameToShow ASC;
endif

:LIMIT topN;

:WITH COLUMN top = ROW_NUMBER();

:Return Right(DataFrame);

stop
@enduml
