@startuml
actor User

participant "DataReformatter" as DATA_REFORMAT
participant "AemetDataReformatter" as AEMET_REFMT
participant "IfapaDataReformatter" as IFAPA_REFMT
participant "Storage" as STORAGE
participant "JSONStorageBackend" as JSON_STORAGE_BACKEND
participant "AvroParquetBackend" as PARQUET_STORAGE_BACKEND

== DATA REFORMAT ==

User -> DATA_REFORMAT : reformatData()
activate DATA_REFORMAT

' --- Reformat AEMET stations ---
DATA_REFORMAT -> AEMET_REFMT : reformatStationsData()
activate AEMET_REFMT
AEMET_REFMT -> JSON_STORAGE_BACKEND : readJSON(stations metadata) and readJSON(stations data)
JSON_STORAGE_BACKEND --> AEMET_REFMT : stations data and metadata JSONs
loop for each station in stations JSON
  AEMET_REFMT -> PARQUET_STORAGE_BACKEND: put(station record)
  PARQUET_STORAGE_BACKEND --> AEMET_REFMT : written
end
AEMET_REFMT --> DATA_REFORMAT : done
deactivate AEMET_REFMT

' --- Reformat AEMET meteo ---
DATA_REFORMAT -> AEMET_REFMT : reformatMeteoData()
activate AEMET_REFMT
AEMET_REFMT -> STORAGE : readDirectoryRecursive(meteo files dir)
STORAGE --> AEMET_REFMT : meteo file list
AEMET_REFMT -> AEMET_REFMT : buildChunks(meteo file list)
loop for each chunk in chunks
  loop for each file in chunk
    AEMET_REFMT -> JSON_STORAGE_BACKEND : readJSON(meteo file)
    JSON_STORAGE_BACKEND --> AEMET_REFMT : written
    loop for each record in file
      AEMET_REFMT -> PARQUET_STORAGE_BACKEND : put(meteo record)
      PARQUET_STORAGE_BACKEND --> AEMET_REFMT : written
    end
  end
end
AEMET_REFMT --> DATA_REFORMAT : done
deactivate AEMET_REFMT

' --- Reformat IFAPA stations ---
DATA_REFORMAT -> IFAPA_REFMT : reformatStationsData()
activate IFAPA_REFMT
IFAPA_REFMT -> JSON_STORAGE_BACKEND : readJSON(station metadata) and readJSON(station data)
JSON_STORAGE_BACKEND --> IFAPA_REFMT : stations data and metadata JSONs
IFAPA_REFMT -> PARQUET_STORAGE_BACKEND : put(station record)
PARQUET_STORAGE_BACKEND --> IFAPA_REFMT : written
IFAPA_REFMT --> DATA_REFORMAT : done
deactivate IFAPA_REFMT

' --- Reformat IFAPA meteo ---
DATA_REFORMAT -> IFAPA_REFMT : reformatMeteoData()
activate IFAPA_REFMT
IFAPA_REFMT -> JSON_STORAGE_BACKEND : readJSON(meteo data)
JSON_STORAGE_BACKEND --> IFAPA_REFMT : meteo data JSON
loop for each record in meteo JSON
  IFAPA_REFMT -> PARQUET_STORAGE_BACKEND : put(meteo record)
  PARQUET_STORAGE_BACKEND --> IFAPA_REFMT : written
end
IFAPA_REFMT --> DATA_REFORMAT : done
deactivate IFAPA_REFMT

DATA_REFORMAT --> User : end reformatData()
deactivate DATA_REFORMAT

@enduml
